[build]
  command = "cd client && bun install && bun run build"
  publish = "client/dist"

[functions]
  directory = "server/functions"

[dev]
  port = 8888
  command = "cd client && bun run dev"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
